apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  labels:
    app.kubernetes.io/name: postgres
data:
  init.sql: |
    {{- range .Values.postgres.databases }}
    CREATE DATABASE {{ . }};
    {{- end }}
