{{- if .Values.global.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.secret.name }}
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  postgres-password: {{ .Values.global.secret.postgresPassword | quote }}
  postgres_user: {{ .Values.global.secret.postgresUser | quote }}
  postgres_db: {{ .Values.global.secret.postgresDb | quote }}
  keycloak-admin-password: {{ .Values.global.secret.keycloakAdminPassword | quote }}
{{- end }}
